SRQ_QUESTIONS = [
    "Apakah Anda sering merasa sakit kepala?",
    "Apakah Anda kehilangan nafsu makan?	",
    "Apakah tidur Anda tidak nyenyak?",
    "Apakah anda mudah merasa takut?",
    "Apakah Anda merasa cemas, tegang, atau khawatir?",
    "Apakah tangan Anda gemetar?",
    "Apakah Anda mengalami gangguan pencernaan?",
    "Apakah Anda merasa sulit berpikir jernih?",
    "Apakah Anda merasa tidak bahagia?",
    "Apakah Anda lebih sering menangis?",
    "Apakah Anda merasa sulit untuk menikmati aktivitas sehari-hari?",
    "Apakah Anda mengalami kesulitan untuk mengambil keputusan?",
    "Apakah aktivitas/tugas sehari-hari anda terbengkalai?",
    "Apakah Anda merasa tidak mampu berperan dalam kehidupan ini?",
    "Apakah Anda kehilangan minat terhadap banyak hal?",
    "Apakah Anda merasa tidak berharga?",
    "Apakah Anda mempunyai pikiran untuk mengakhiri hidup anda?",
    "Apakah Anda merasa lelah sepanjang waktu?",
    "Apakah Anda merasa tidak enak di perut?",
    "Apakah Anda mudah lelah?",
    "Apakah Anda minum alkohol lebih banyak dari biasanya atau apakah anda menggunakan narkoba?",
    "Apakah anda yakin bahwa seseorang mencoba mencelakai anda dengan cara tertentu?",
    "Apakah ada yang mengganggu atau hal yang tidak biasa dalam pikiran anda?",
    "Apakah anda pernah mendengar suara tanpa tahu sumbernya atau yang orang lain tidak dapat mendengar?",
    "Apakah anda mengalami mimpi yang mengganggu tentang suatu bencana/musibah atau adakah saat-saat anda seolah mengalami kembali kejadian bencana itu?",
    "Apakah anda menghindari kegiatan, tempat, orang atau pikiran yang mengingatkan anda akan bencana tersebut?",
    "Apakah minat anda terhadap teman dan kegiatan anda yang biasa anda lakukan berkurang?",
    "Apakah anda merasa sangat terganggu jika berada dalam situasi yang mengingatkan anda akan bencana atau jika anda berpikir tentang bencana itu?",
    "Apakah anda kesulitan memahami atau mengekspresikan perasaan anda?",
]

SRQ_RECOMMENDATIONS = [
    "Perbanyak istirahat, minum air putih yang cukup, dan lakukan relaksasi ringan.",
    "Cobalah makan teratur dengan porsi kecil namun sering, dan perhatikan asupan bergizi.",
    "Atur jadwal tidur yang konsisten, kurangi penggunaan gawai sebelum tidur.",
    "Latih teknik pernapasan dalam dan cari lingkungan yang membuat Anda merasa aman.",
    "Luangkan waktu untuk relaksasi, seperti meditasi singkat atau aktivitas menenangkan.",
    "Cobalah peregangan ringan dan latihan pernapasan untuk mengurangi ketegangan.",
    "Perhatikan pola makan dan hindari makanan yang memicu gangguan pencernaan.",
    "Beri jeda saat beraktivitas dan lakukan latihan fokus sederhana.",
    "Cobalah menuliskan perasaan Anda dan berbagi cerita dengan orang terpercaya.",
    "Ekspresikan emosi dengan cara sehat, seperti menulis atau berbicara dengan orang terdekat.",
    "Mulailah dari aktivitas kecil yang menyenangkan dan tingkatkan secara bertahap.",
    "Buat daftar prioritas sederhana untuk membantu pengambilan keputusan.",
    "Susun jadwal harian yang realistis dan selesaikan tugas satu per satu.",
    "Ingat kembali peran dan kontribusi positif yang pernah Anda lakukan.",
    "Cobalah aktivitas baru yang ringan untuk memunculkan kembali minat.",
    "Latih afirmasi positif dan hindari membandingkan diri dengan orang lain.",
    "Segera cari bantuan profesional atau hubungi layanan konseling/dukungan terdekat.",
    "Atur waktu istirahat yang cukup dan hindari aktivitas berlebihan.",
    "Perhatikan pola makan dan kelola stres yang dapat memengaruhi pencernaan.",
    "Seimbangkan aktivitas dan istirahat, serta jaga kualitas tidur.",
    "Pertimbangkan untuk mengurangi konsumsi alkohol/narkoba dan cari dukungan profesional.",
    "Bicarakan pengalaman ini dengan tenaga profesional untuk mendapatkan bantuan tepat.",
    "Catat hal-hal yang mengganggu pikiran dan diskusikan dengan konselor.",
    "Segera konsultasikan dengan tenaga kesehatan mental untuk evaluasi lebih lanjut.",
    "Lakukan teknik grounding dan pertimbangkan konseling trauma.",
    "Mulailah perlahan menghadapi pemicu dengan pendampingan profesional.",
    "Coba kembali berinteraksi secara bertahap dengan teman atau kegiatan ringan.",
    "Latih teknik relaksasi saat menghadapi pemicu dan cari dukungan profesional.",
    "Latih komunikasi emosi secara bertahap, misalnya melalui menulis atau konseling.",
]

FALLBACK_RECOMMENDATIONS_ALERT = [
    "Segera hubungi layanan konseling kampus.",
    "Bicarakan kondisi Anda dengan orang terdekat yang dipercaya.",
    "Kurangi beban akademik sementara jika memungkinkan.",
]

FALLBACK_RECOMMENDATIONS_SAFE = [
    "Jaga pola tidur, makan, dan aktivitas fisik secara konsisten.",
    "Pertahankan manajemen stres yang baik dan rutinitas belajar seimbang.",
    "Tetap lakukan self-check kesehatan mental secara berkala.",
]
